version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_clinique
    restart: always
    environment:
      - MYSQL_DATABASE=clinique
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3309:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: spring_app_clinique
    ports:
      - "8080:8080"
    volumes:
      - ./mes-pdfs:/app/pdf_ordonnances
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/clinique
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=